builds:
  - main: ./cmd/arconn/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ruelala/arconn/pkg/utils.binary=arconn
      - -s -w -X github.com/ruelala/arconn/pkg/utils.commit={{.Commit}}
      - -s -w -X github.com/ruelala/arconn/pkg/utils.date={{.Date}}
      - -s -w -X github.com/ruelala/arconn/pkg/utils.version={{.Version}}

changelog:
  sort: desc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

archives:
  - id: default
    format: zip
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
