builds:
  - main: ./cmd/arconn/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ruelala/arconn/pkg/utils.version={{.Version}}
      - -s -w -X github.com/ruelala/arconn/pkg/utils.commit={{.Commit}}
      - -s -w -X github.com/ruelala/arconn/pkg/utils.date={{.Date}}

changelog:
  sort: desc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
